# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_get_nb_threads <- function() {
    .Call(`_DRDID_cpp_get_nb_threads`)
}

cpppar_exp <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_exp`, x, nthreads)
}

cpppar_log <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_log`, x, nthreads)
}

cpppar_log_a_exp <- function(nthreads, a, mu, exp_mu) {
    .Call(`_DRDID_cpppar_log_a_exp`, nthreads, a, mu, exp_mu)
}

cpppar_lgamma <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_lgamma`, x, nthreads)
}

cpppar_digamma <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_digamma`, x, nthreads)
}

cpppar_trigamma <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_trigamma`, x, nthreads)
}

cpppar_poisson_linkinv <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_poisson_linkinv`, x, nthreads)
}

cpppar_poisson_validmu <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_poisson_validmu`, x, nthreads)
}

cpppar_logit_linkfun <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_logit_linkfun`, x, nthreads)
}

cpppar_logit_linkinv <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_logit_linkinv`, x, nthreads)
}

cpppar_logit_mueta <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_logit_mueta`, x, nthreads)
}

cpppar_logit_devresids <- function(y, mu, wt, nthreads) {
    .Call(`_DRDID_cpppar_logit_devresids`, y, mu, wt, nthreads)
}

cpppar_xwy <- function(X, y, w, nthreads) {
    .Call(`_DRDID_cpppar_xwy`, X, y, w, nthreads)
}

cpppar_xbeta <- function(X, beta, nthreads) {
    .Call(`_DRDID_cpppar_xbeta`, X, beta, nthreads)
}

cpppar_matprod <- function(x, y, nthreads) {
    .Call(`_DRDID_cpppar_matprod`, x, y, nthreads)
}

cpppar_which_na_inf_vec <- function(x, nthreads) {
    .Call(`_DRDID_cpppar_which_na_inf_vec`, x, nthreads)
}

cpppar_which_na_inf_mat <- function(mat, nthreads) {
    .Call(`_DRDID_cpppar_which_na_inf_mat`, mat, nthreads)
}

cpppar_which_na_inf_df <- function(df, nthreads) {
    .Call(`_DRDID_cpppar_which_na_inf_df`, df, nthreads)
}

cpppar_cond_means <- function(mat_vars, treat, nthreads = 1L) {
    .Call(`_DRDID_cpppar_cond_means`, mat_vars, treat, nthreads)
}

cpppar_check_only_0 <- function(x_mat, nthreads) {
    .Call(`_DRDID_cpppar_check_only_0`, x_mat, nthreads)
}

